# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c9de5b5142d81b683a23cbd57ba86ed5a7dbe4658d3ce87c165c1f51379f297212abcb6252070fa2bdb535fd994f6ecf2f7ac26808c0c6fe069502944e89fc

test:
  secret_key_base: db885ef8adcde1821ede889bcd5d8c92c3859bd0127d474524d3a13290b3d54b03ae43a5b1ed2a363476026104668c1ae13c0335c5d972b4b0a0bddd8e598a10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
